```python
# default_template.py

# This is a default template for Python Advanced Structure Synthesizer (PASS)

# Import necessary libraries
import os
from config import *

def create_default_structure():
    """
    Function to create a default project structure.
    """
    # Create the base directory for the project
    base_dir = os.path.join(OUTPUT_DIR, DEFAULT_PROJECT_NAME)
    os.makedirs(base_dir, exist_ok=True)

    # Create the specified number of directories and files
    for i in range(DEFAULT_NUM_DIRS):
        dir_path = os.path.join(base_dir, f"dir_{i}")
        os.makedirs(dir_path, exist_ok=True)

        for j in range(DEFAULT_NUM_FILES):
            file_path = os.path.join(dir_path, f"file_{j}.py")
            with open(file_path, 'w') as f:
                f.write("# This is a Python file generated by PASS using the default template")

if __name__ == "__main__":
    create_default_structure()
```
